config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "welcome/say_hello" => "welcome#say"
  # ...
  get "welcome" => "welcome#index"
  root :to => "posts#index"

  resources :posts do
    resources :comments, except: :show
  end

  resources :categories

  # project ticket
  resources :tickets

end

app/models/add_comments_count_to_post.rb
class AddCommentsCountToPost < ApplicationRecord
end

app/models/add_delete_at_to_post.rb
class AddDeleteAtToPost < ApplicationRecord
end

app/models/add_user_id_to_comment.rb
class AddUserIdToComment < ApplicationRecord
end

app/models/add_user_id_to_post.rb
class AddUserIdToPost < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :post_category_ships, dependent: :restrict_with_exception
  has_many :posts, through: :post_category_ships
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post, counter_cache: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { where(delete_at: nil) }
  validates :title, presence: true
  validates :content, presence: true


  has_many :comments
  has_many :post_category_ships
  has_many :categories, through: :post_category_ships
  belongs_to :user

  def destroy
    update(delete_at: Time.now)
  end
end

app/models/post_category_ship.rb
class PostCategoryShip < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :age, presence: true
  validates :country, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit ;end

  def update
    if @category.update(params_category)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:name)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :validate_comment_owner, only:[:edit, :update, :destroy]


  def index
    @comments = @post.comments.page(params[:page]).per(10)
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(params_comment)
    @comment.user = current_user
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new
    end

  end

  def edit; end

  def update
    if @comment.update(params_comment)
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_comments_path(@post)
  end

  private

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def params_comment
    params.require(:comment).permit(:content)
  end

  def validate_comment_owner
    unless @comment.user == current_user
      flash[:notice] = 'The comment does not belongs to you'
      redirect_to posts_comments_path(@post)
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :validate_post_owner, only:[:edit, :update, :destroy]

  def index
    @posts = Post.includes(:categories, :user).page(params[:page]).per(10)
  end


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def update
    if @post.update(params.require(:post).permit(:title, :content))
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, category_ids: [])
  end

  def validate_post_owner
    unless @post.user == current_user
      flash[:notice] = 'The post not belongs to you'
      redirect_to posts_path
    end

  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def new

    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(params.require(:ticket).permit(:name, :email, :age, :country))
    if @ticket.save
      redirect_to tickets_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def update
    if @ticket.update(params.require(:ticket).permit(:name, :email, :age, :country))
      redirect_to tickets_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :email, :age, :country)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def say

  end

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, url: path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Category id: <%= @category.id %></h1>
<%= render partial: 'form', locals: { category: @category, path: category_path(@category)} %>

app/views/categories/index.html.erb
<h1>Category</h1>

<ul>
  <% @categories.each do |category| %>
  <li>
    <%= category.name %>
    <%= link_to :edit, edit_category_path(category) %>
    <%= button_to :delete, category_path(category), method: :delete %>
  <% end %>
  </li>

</ul>

<%= link_to 'New', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, data: { turbo: false } do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit%>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.title %></h1>
<h2>edit comment id: <%= @comment.id %></h2>
<%= render partial: 'form', locals: {post: @post, comment: @comment, path: post_comment_path(@post, @comment)} %>

app/views/comments/index.html.erb
<h1>Title <%= @post.title %></h1>
<h2>Comments</h2>
<ul>
  <% @comments.each do |comment| %>
  <li><%= comment.content %>(<%= comment.created_at %>) by <%= comment.user.email %>
    <%= link_to 'edit', edit_post_comment_path(@post, comment) if comment.user == current_user%>
    <%= button_to 'delete', post_comment_path(@post, comment), method: :delete if comment.user == current_user%>

  </li>
  <% end %>
</ul>
<%= paginate @comments %>

<%= link_to 'New Comment', new_post_comment_path %>
<%= link_to 'Post list', posts_path %>

app/views/comments/new.html.erb
<h1>Title: <%= @post.title %></h1>
<%= render partial: 'form', locals: {post: @post, comment: @comment, path: post_comments_path(@post)} %>
<%= link_to 'Back', posts_path %>

app/views/posts/_form.html.erb
    <%= form_with model: @post do |form| %>
      <% if @post.errors.any? %>
        <ul>
          <% @post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      <% end %>
      <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>
      <div>
        <%= form.label :content %>
        <%= form.text_field :content %>
      </div>
      <div>
        <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
      </div>
      <%= form.submit %>
    <% end %>

app/views/posts/edit.html.erb
<h1>Edit Post id: <%= @post.id %></h1>

<%= render partial: 'form', locals: {post: @post} %>

app/views/posts/index.html.erb
<div class="list-containers">
<h1>Post List</h1>

<table id="customers">
  <thead>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>User</th>
    <th>Category</th>
    <th>Count</th>
    <th>Actions</th>
  </tr>


  </thead>
  <% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.user&.email %></td>
    <td><%= post.categories.pluck(:name).join(',') %></td>
    <td><%= post.comments_count %></td>
    <td>
      <%= link_to 'Show', post_path(post) %>
      <%= link_to 'Edit', edit_post_path(post) if post.user == current_user %>
      <%= button_to 'Delete', post_path(post), method: :delete if post.user == current_user%>
      <%= link_to 'comments', post_comments_path(post) %>
    </td>
  </tr>
  <% end %>
</table>
<%= paginate @posts %>

<div class="create-new">
  <%= link_to 'New', new_post_path, class: "create" %>
</div>

</div>

app/views/posts/new.html.erb
<h1>New Posts</h1>
<%= render partial: 'form', locals: {post: @post} %>
<%= link_to 'Index', posts_path %>

app/views/posts/show.html.erb
<h1>show post id: <%= @post.id %></h1>
<ul>
  <li><%= @post.title %></li>
  <li><%= @post.content %></li>
</ul>

<%= link_to 'Index', posts_path %>

app/views/tickets/edit.html.erb
<div class="container">
  <div class="form-wrap">
    <%= form_with model: @ticket do |form| %>
      <% if @ticket.errors.any? %>
        <ul>
          <% @ticket.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="name-field">
        <label for="name">Name</label>
        <%= form.text_field :name %>
      </div>
      <div>
        <label for="email">Email</label>
        <%= form.text_field :email %>
      </div>
      <div>
        <label for="age">Age</label>
        <%= form.number_field :age %>
      </div>

      <div>
        <label for="country">Country</label>
        <%= form.text_field :country %>
      </div>

      <div>
        <%= form.date_field :date%>
      </div>

      <div class="btn">
        <%= form.submit 'Update', class: 'update-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="list-container">
  <h1>Customer Lists</h1>

  <table id="customers">
    <thead>
    <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Age</th>
    <th>Country</th>
    <th>Actions</th>
    </tr>
    </thead>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.email %></td>
        <td><%= ticket.age %></td>
        <td><%= ticket.country %></td>
        <td>
          <%= link_to 'Show', ticket_path(ticket) %>
          <%= link_to 'Edit', edit_ticket_path(ticket) %>
          <%= button_to 'Delete', ticket_path(ticket), method: :delete %>
        </td>
      </tr>
    <% end %>
  </table>

  <div class="create-new">
    <%= link_to 'Book', new_ticket_path, class: "create" %>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <div class="form-wrap">
    <%= form_with model: @ticket do |form| %>
      <% if @ticket.errors.any? %>
        <ul>
          <% @ticket.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="name-field">
        <label for="name">Name</label>
        <%= form.text_field :name %>
      </div>
      <div>
        <label for="email">Email</label>
        <%= form.text_field :email %>
      </div>
      <div>
        <label for="age">Age</label>
        <%= form.number_field :age %>
      </div>

      <div>
        <label for="country">Country</label>
        <%= form.text_field :country %>
      </div>

      <div>
        <%= form.date_field :date %>
      </div>

      <div class="btn">
        <%= form.submit 'Book', class: 'test' %>
      </div>
    <% end %>

    <%= link_to 'Back', tickets_path %>
  </div>
</div>

app/views/tickets/show.html.erb
<body style="background: #730E15;">
<div class="receipt-container">
  <div id="ticket-wrap">

    <div class="content">
      <div id="header-receipt">
        <h2>Receipt</h2>
        <p>Address: #123 Jan lang sa tabi-tabi st.</p>
        <p>Telephone No: 861-1512</p>
      </div>

      <hr class="tickets">
      <div class="receipt-content">
        <p id="date"><%= @ticket.created_at %></p>
        <p class="info"><%= @ticket.name %></p>
        <p class="info"><%= @ticket.email %></p>
        <p class="info"><%= @ticket.age %></p>
        <p class="info"><%= @ticket.country %></p>
      </div>


      <hr class="tickets">

      <h2>Thank you!</h2>

      <div class="barcode">
        <span class="lg-l"></span>
        <span class="sm-l"></span>
        <span class="xs-l"></span>
        <span class="md-l"></span>
        <span class="md-l"></span>
        <span class="xs-l"></span>
        <span class="lg-l"></span>
        <span class="xs-l"></span>
        <span class="sm-l"></span>
        <span class="xs-l"></span>
        <span class="lg-l"></span>
        <span class="md-l"></span>
        <span class="xs-l"></span>
        <span class="sm-l"></span>
        <span class="xs-l"></span>
        <span class="xs-l"></span>
        <span class="lg-l"></span>
        <span class="sm-l"></span>
        <span class="sm-l"></span>
        <span class="md-l"></span>
        <span class="xl-l"></span>
        <span class="xs-l"></span>
        <span class="xl-l"></span>
        <span class="sm-l"></span>
        <span class="sm-l"></span>
        <span class="sm-l"></span>
        <span class="xs-l"></span>
        <span class="md-l"></span>
        <span class="xs-l"></span>
        <span class="xs-l"></span>

        <p>
          <%= link_to 'Ok', tickets_path %>
        </p>
      </div>
    </div>
  </div>
</div>
</body>